# Generated by Django 5.0.1 on 2024-03-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_recenzie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzie',
            name='titlu',
            field=models.CharField(max_length=20),
        ),
    ]
