# Generated by Django 5.0.1 on 2024-03-10 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_recenzie_titlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
