# Generated by Django 5.0.1 on 2024-04-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_intrebare_text_raspuns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorit',
            options={'verbose_name_plural': 'about'},
        ),
    ]
