# Generated by Django 5.0.1 on 2024-04-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_favorit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorit',
            options={'verbose_name_plural': 'Favorit'},
        ),
        migrations.AlterModelOptions(
            name='intrebare',
            options={'verbose_name_plural': 'Intrebare'},
        ),
        migrations.AlterModelOptions(
            name='producator',
            options={'verbose_name_plural': 'Producator'},
        ),
        migrations.AlterModelOptions(
            name='produs',
            options={'verbose_name_plural': 'Produs'},
        ),
        migrations.AlterModelOptions(
            name='recenzie',
            options={'verbose_name_plural': 'Recenzie'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfile'},
        ),
    ]
