# Generated by Django 5.0.1 on 2024-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefon',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
